# name: 🚀 Release

# on:
#   push:
#     branches:
#       - main

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Nécessaire pour analyser l'historique des commits

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22.13.0'

#       - name: Install dependencies
#         run: npm install

#       - name: Run Semantic Release
#         run: npx semantic-release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
