name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Permet de le lancer manuellement aussi

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
            config: config-cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.git-cliff.outputs.version }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}
          draft: false
          prerelease: false
